### ISSUE TITLE
FR12. Spashscreen

### ISSUE THREAD

**Issue by KrisCovert** [WSU-4110/SmartShopper#4]
|FR12.  Spashscreen|
|---|
|**Goal**: To allow the user to load right into the application making it an easy experience.
**Stakeholders:** Grocery Shoppers|
| **Description:** Most applications have the user make an account and go through an initial set up to use the app. By making ours boot up to a splashscreen the users are able to get into the application right away making the functionality of the app that much easier for the user. |
| **Origin:** The idea was brought up during the first meeting on 1/31/2021|
| **Version:** 1.0  |  
|**Date:** 01/31/2021  
|  **Priority:** 9 |

**Comment by justincrawford-wsu** [comment]
Splashscreen is finished, but we were not able to implement it into this version of the app.

**Comment by Adrian-Tarnowski** [comment]
Splashscreen is integrated into this project. We are closing this because the splash screen works, we just chose not to implement it within this version.

**Comment by lustyun** [comment]
The splashscreen can be viewed manually from the main page.
